### ISSUE TITLE
I dont understand how to install it

### ISSUE THREAD

**Issue by tartarica** [AlexPetrusca/Mephisto#1]
Can you explain me how to install this extension, please?

**Comment by Dhanamerdeka** [comment]
same

**Comment by Dhanamerdeka** [comment]
ahh nevermind i realize how to use it lol

**Comment by mikhailhaimovich** [comment]
> ahh nevermind i realize how to use it lol

How did you get it working?

**Comment by JanKerbl** [comment]
How does it work?
