### ISSUE TITLE
Loading the Extention

### ISSUE THREAD

**Issue by kaballas** [AlexPetrusca/Mephisto#7]
Hi I am getting the following error when trying to load the code
![image](https://user-images.githubusercontent.com/30285763/182548693-d581acab-ac04-42ad-a7a2-b81e961679c6.png)
Thanks
Theo

**Comment by AlexPetrusca** [comment]
Can you try with release v1.0.0? https://github.com/AlexPetrusca/Mephisto/releases/tag/Latest
